spring.application.name=portfolio
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/portfolio_db

# Email Services SMTP (Verified 16-Digit App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ragul31032005@gmail.com
spring.mail.password=qvgrwzzuukbjihqb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Dynamic Dev Environment Filters
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.thymeleaf.cache=false